### ISSUE TITLE
window.$.ajax should return a jqxhr-like object

### ISSUE THREAD

**Issue by liorch88** [walmartlabs/fruit-loops#54]
The window.$.ajax function currently returns a simple xhr-like object. However, since we are expecting it to act like jquery's ajax, it should return a promise/deferred object with methods such as "done" and "then". 
Otherwise using backbone code such as:
`MyModel.fetch().done(fuction() ...)` 
doesn't work.

**Comment by kpdecker** [comment]
Fully support getting this in. I have not had time to look at this but if you wanted to do a PR that would certainly make it happen faster. The same applies to #55.

**Comment by liorch88** [comment]
I don't believe I will have time for this either in the near future. Any suggested workarounds?
